Added online shopping site tests
KaterinBaranova/Online_Shopping_Site_Diploma pull request #1
Opened 2022-02-11 18:17 UTC by KaterinBaranova

2022-02-12 21:34 UTC, voropa requested changes

2022-02-12 21:34 UTC, voropa commented on README.md
> +-----------------------------------------------------------------------------------------------------------------------------------------------------
А где чеклист?)

2022-02-12 21:34 UTC, voropa commented on src/test/java/pages/BasePage.java
> +public abstract class BasePage <T extends LoadableComponent<T>> extends LoadableComponent<T> {
Уверена, что сможешь обьяснить что это  такое, как это работает и зачем это нужно?

2022-02-12 21:34 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    public abstract void login(String login, String password);
Зачем эти методы тут, еще и абстрактыне? Предполагается, что  они могут быть по-разному реализованы в разных классах-наследниках? 
Думаю, что метод login будет везде одинаковый....

2022-02-12 21:34 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    public abstract boolean deletelWishlist(String wishlistName);
То же самое

2022-02-12 21:34 UTC, voropa commented on src/test/java/pages/CartHoverPage.java
> +    @Override
Я не понимаю, зачем в каждый класс-наследник тянуть эти методы, если фактически они нигде не переопределяются, а реализация всегда пустая....

2022-02-12 21:34 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +        return Integer.parseInt(itemsInCart.getText().replaceAll("[^0-9.]", ""));
Решение можно  упростить с помощью метода String. charAt(), если мы знаем, что необходимая цифра всегда на первом месте в возвращаемой строке

2022-02-12 21:34 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +        getActions().click(checkOutBtn);
Что за длинный набор действий,  похожий на тестовый сценарий. Вероятно это должно быть в тест-классе, а не в page классе

2022-02-12 21:34 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +        private final String columnName;
enum'ы лучше выносить в отдельные файлы, чтобы их потом можно  было переиспользовать в других классах

2022-02-13 06:26 UTC, KaterinBaranova commented on README.md
> +-----------------------------------------------------------------------------------------------------------------------------------------------------
Added checklist to README file.

2022-02-13 06:47 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +        return Integer.parseInt(itemsInCart.getText().replaceAll("[^0-9.]", ""));
Updated CheckOutPage to use String. charAt().

2022-02-13 07:53 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +        private final String columnName;
Created separate files for enums.

2022-02-13 08:18 UTC, KaterinBaranova commented on src/test/java/pages/BasePage.java
> +    public abstract void login(String login, String password);
Removed unnecessary methods.

2022-02-13 08:18 UTC, KaterinBaranova commented on src/test/java/pages/BasePage.java
> +    public abstract boolean deletelWishlist(String wishlistName);
Removed unnecessary methods.

2022-02-13 08:41 UTC, KaterinBaranova commented on src/test/java/pages/BasePage.java
> +public abstract class BasePage <T extends LoadableComponent<T>> extends LoadableComponent<T> {
Removed <T extends LoadableComponent<T>> extends LoadableComponent<T> and related code in pages.

2022-02-13 08:59 UTC, KaterinBaranova commented on src/test/java/pages/CartHoverPage.java
> +    @Override
Edited.

2022-02-13 11:00 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +        getActions().click(checkOutBtn);
Moved the test data to the test class

2022-02-13 20:25 UTC, voropa requested changes

2022-02-13 20:25 UTC, voropa commented on src/test/java/pages/ItemPage.java
> +    public static final String ITEM_URL = "http://prestashop.qatestlab.com.ua/en/tshirts/1-faded-short-sleeve-tshirts.html";
Почему в ItemPage захардкожен URL к конкретной вещи в каталоге. page-класс штука абсьтрактная, ему должно  быть  без разницы какой товар выбран, он должн уметь работать с любым. А вот конкретный товар, его название или ссылка - это уже тестовые данные, которые должны быть в test-классе, а не page классе

2022-02-13 20:25 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +        getActions().isElementTextChanged(itemsInCart, originalText);
Мтеод называется pressIncreaseQuantity  и он внутри нажимает эту кнопку, но затем
идет строчка getActions().isElementTextChanged(itemsInCart, originalText), которая возвращает boolean значение и ты с ним ничег оне длаешь, не проверяешь, что оно true и не пробрасываешь его дальше через return.  Вопрос: зачем тогда вызывать этот  isElementTextChanged тут, если он ничего не делает и неважно что он вернет true или false

2022-02-13 20:25 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +            getActions().isElementTextChanged(itemsInCart, originalText);
То же самое с isElementTextChanged

2022-02-13 20:25 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +        checkOutBtn.click();
1. Тестовые данные должны передаваться в качестве входных аргументов в  метод, а не хардкодится
2. Это все еще похоже на тестовый сценарий, так почему он в page классе??
Из контекста я понял, что тут заполняются данные на checkout форме, тогда сделай метод типа fillCheckoutForm(). который будет принимать все данные в качестве входных аргументов и прост заполнять форму данными. А все действия по  типу         
        saveBtn.click();
        proceedToCheckOutBtn.click();
        termsOfServiceCheckbox.click();
        completeOrder.click();
Должны быть отдельными методами и потом вызываться в тесте. 
соответсвенно тест должен будет выглядеть как то так:
@Test
.....
loginPage.login();
#add items to cart
.....
checkoutPage.fillForm(......)
checkoutPage.clickSavebutton();
checkoutPage.clickProccedToCheckoutButton();
.,......

2022-02-13 20:25 UTC, voropa commented on src/test/java/pages/WishlistPage.java
> +    private WebElement firstTopSellingItem;
Плохой локатор
если хочешь в тесте всегда выбирать первую вещь, то лучше получить сначала коллецию всех вещей через List<WebElements> и из нее выбрать первый с помощью get(0);

2022-02-13 20:25 UTC, voropa commented on src/test/java/setup/Action.java
> +    static final Integer DEFAULT_TIMEOUT = Integer.parseInt(System.getProperty("selenium.defaultTimeout", "5"));
А у тебя точно есть такая системная переменная? Думаю, что этот код бесполезен)

2022-02-13 20:25 UTC, voropa commented on src/test/java/pages/WishlistPage.java
> +        getActions().isPageReady();
Опять же таки, в чем смысл вызывать этот boolean метод, если его результат никак не обрабатывается?

2022-02-13 20:25 UTC, voropa commented on src/test/java/tests/CartHoverTest.java
> +        ItemPage itemPage = new ItemPage(driver);
Инициализацию пэйджей через new лучше делать в before методах, чтобы не засорять сам тест и он был более читабельный

2022-02-13 20:25 UTC, voropa commented on src/test/java/tests/CheckOutTest.java
> +        driver.get("http://prestashop.qatestlab.com.ua/en/blouses/2-blouse.html#/size-s/color-black");
1. Плохо, что URL к конкретному товару у тебя захардкожен в тесте, он может поменяться и тогда тест упадет
2. НА сколкьо я понимаю для проверки колличества товаров нам неважно какой товар в корзине, так что можно добавлять любой.
Соотвественно товары лучше добавлять по  имени, а не хардкодить URL'ы к ним

2022-02-13 20:25 UTC, voropa commented on src/test/java/tests/ItemTest.java
> +        assertEquals("http://prestashop.qatestlab.com.ua/en/tshirts/1-faded-short-sleeve-tshirts.html#/size-s/color-blue", itemPage.getUrl(), "Images are not filtered based on color");
Плохая проверка. Она не достаточная. В url может быть написано что угодно, а на экоране ничего не отображается...
Так что  проверять нужно все айтемы на экране, что у них действительно цвет соответсвует фильтру

2022-02-13 20:25 UTC, voropa commented on src/test/java/tests/SignInTest.java
> +    public void signInWithEmptyLoginTest() {
все негативные логин тесты можно сделать data driven с помощью data provider, потому что они отличаются только входными данными

2022-02-13 20:25 UTC, voropa commented on src/test/java/pages/SignInPage.java
> +    public void signInLink() {
Название метода должно быть глаголом, потому что это действие

2022-02-13 20:25 UTC, voropa commented on src/test/java/pages/ItemPage.java
> +    public boolean getFancyBoxText() {
Почему этот метод всегда возвращает true? А по названию он должен возвращать какой-то текст....

2022-02-13 21:22 UTC, KaterinBaranova commented on src/test/java/pages/SignInPage.java
> +    public void signInLink() {
Updated method name to be a verb

2022-02-13 21:42 UTC, KaterinBaranova commented on src/test/java/pages/ItemPage.java
> +    public static final String ITEM_URL = "http://prestashop.qatestlab.com.ua/en/tshirts/1-faded-short-sleeve-tshirts.html";
Transferred test url from ItemPage to ItemTest.

2022-02-13 22:24 UTC, KaterinBaranova commented on src/test/java/pages/ItemPage.java
> +    public boolean getFancyBoxText() {
Edited getFancyBoxText method not to return true.

2022-02-13 22:31 UTC, KaterinBaranova commented on src/test/java/tests/ItemTest.java
> +        assertEquals("http://prestashop.qatestlab.com.ua/en/tshirts/1-faded-short-sleeve-tshirts.html#/size-s/color-blue", itemPage.getUrl(), "Images are not filtered based on color");
Updated assert in selectColorTest.

2022-02-13 22:42 UTC, KaterinBaranova commented on src/test/java/pages/WishlistPage.java
> +        getActions().isPageReady();
Delete unnecessary boolean from the method

2022-02-14 08:12 UTC, KaterinBaranova commented on src/test/java/tests/CartHoverTest.java
> +        ItemPage itemPage = new ItemPage(driver);
Moved page initialization in before methods.

2022-02-14 08:43 UTC, KaterinBaranova commented on src/test/java/pages/WishlistPage.java
> +    private WebElement firstTopSellingItem;
Updated wishlist test to avoid using a bad locator.

2022-02-14 08:48 UTC, KaterinBaranova commented on src/test/java/tests/CheckOutTest.java
> +        driver.get("http://prestashop.qatestlab.com.ua/en/blouses/2-blouse.html#/size-s/color-black");
Removed hardcoded url from tests.

2022-02-14 09:24 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +        getActions().isElementTextChanged(itemsInCart, originalText);
Removed unnecessary code and updated code.

2022-02-14 09:24 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +            getActions().isElementTextChanged(itemsInCart, originalText);
Removed unnecessary code and updated code.

2022-02-14 10:20 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +        checkOutBtn.click();
Updated CheckOut page and CheckOut Test.

2022-02-14 11:23 UTC, KaterinBaranova commented on src/test/java/setup/Action.java
> +    static final Integer DEFAULT_TIMEOUT = Integer.parseInt(System.getProperty("selenium.defaultTimeout", "5"));
Removed unnecessary code and updated code.

2022-02-14 13:25 UTC, KaterinBaranova commented on src/test/java/tests/SignInTest.java
> +    public void signInWithEmptyLoginTest() {
ассерты тоже отличаются "An email address required."/"Password is required.";/"Authentication failed.";  там нету просто login failed , там разные сообщения ошибки. Не очень тогда понимаю смысл этого в даном случае. Если же ожидался один результат при разных наборов то тогда мне понятно а в данном случае не очень

2022-02-15 20:34 UTC, KaterinBaranova commented on src/test/java/tests/SignInTest.java
> +    public void signInWithEmptyLoginTest() {
Added data provider.

2022-02-17 18:09 UTC, voropa requested changes

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +        state.selectByIndex(1);
Хардкоооод
Почему штат всегда первый выбирается? Это же тестовые данные. 
Нужно передавать его в метод selectState (String stateName) в качестве входного аргумента и потом выбирать через selectByVisibleText/selectByValue

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +    public void fillPasswordField(String Password) {
Названия переменных в java пишутся с маленькой буквы. Проверь везде в остальных методах

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +        Select state = new Select(driver.findElement(By.id("id_state")));
Ты же используешь PageFactory. так зачем тогда тут driver.findElement??
Можно же этот элемент инициализировать через @FindBy как и все остальные и передавать его в конструктор класса Select()

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/CartHoverPage.java
> +    private List<WebElement> getCartItems() {
Ты же используешь PageFactory. так зачем тогда тут driver.findElement??
И зачем вообще этот приватный метод? 
можно же инициализировать эту коллекцию элементов через 
@FindBy (locator)
List<WebElements> cartItem;

И потом в методе getCartHoverNumberInCart вызвать cartItem.size()

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/ItemPage.java
> +        List<WebElement> colors = colorOptions.findElements(By.xpath(".//*"));
Что за странный локатор? он ищет любой элемент?

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/ItemPage.java
> +        for (WebElement li : colors) {
что за странное название переменной?

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/ItemPage.java
> +        getActions().isElementDisplayed(cartFrame);
Обсуждали уже это. Эта строчка кода ничег оне делает, так зачем она  тут

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/ItemPage.java
> +    public void proceedToCheckoutButton() {
вероятно, тут в названии метода должно быть слово "click"

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/WishlistPage.java
> +        return getCell(wishlistName) != null;
А разве метод getCell может когда-то вернуть null?
насколько я вижу, он выбросит NoSuchElementException, если не найдет элемент с заданным именем.

Значит проверка в этом методе бессмысленная....

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/WishlistPage.java
> +        List<WebElement> allRows = wishlistTable.findElements(By.xpath("//*[contains(@class,\"table\")]/tbody/tr[*]/td[1]"));
Переделать в @FindBy

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/WishlistPage.java
> +                return wishlistTable.findElement(By.xpath("//*[contains(@class,\"table\")]/tbody/tr[" + rowNumberCounter + "]/td[" + ColumnNumber.NAME.columnNumber + "]"));
Лучше использовать шаблонную строку и String.format() вместо конкатенации через "" + ""

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/WishlistPage.java
> +    private WebElement getCell(String wishlistName) {
Мне кажется, что-то  ты намудрила с локаторами и логикой в этом методе, это явно можно  упростить

2022-02-17 18:09 UTC, voropa commented on src/test/java/tests/CartHoverTest.java
> +        assertEquals(checkOutPage.getItemsInCart(),2);
А почему expected result = 2, вроде в шагах теста добавляли только одну?

2022-02-17 18:09 UTC, voropa commented on src/test/java/tests/CartHoverTest.java
> +    public void checkOutFromHoverTest() {
Описание теста не соответсвует его сценарию и чем он отличается от checkCountInHoverTest?

2022-02-17 18:09 UTC, voropa commented on src/test/java/tests/SignInTest.java
> +    private final static String INVALID_USERNAME = "Katee1@test2.com";
Неправильный порядок полей и методов в классе.
Посмотри code convenction:
https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/ItemPage.java
> +    public void openItem(String productName) {
У page класса ItemPage не может  быт ь метода openItem(), потому что ItemPage  - это та страница, на  которую  мы попадаем, когда делаем openItem().
Соответсвенно у тебя должна быть страница с каталогом товаров, на которую,  вероятно,  ты попадаешь после логина или при открытии сайта,  и вот на ней уже должен  быть метод openItem(), после выполнения которого мы переходим на ItemPage

2022-02-17 18:09 UTC, voropa commented on src/test/java/pages/ItemPage.java
> +        driver.findElement(By.xpath("//a[contains(text(),'" + productName + "')]")).click();
Используй шаблонную строку. Конкатенация - это детский сад)
https://javarush.ru/quests/lectures/questmultithreading.level02.lecture06

2022-02-17 19:18 UTC, KaterinBaranova commented on src/test/java/pages/ItemPage.java
> +    public void proceedToCheckoutButton() {
Changed to click in the method name.

2022-02-17 19:44 UTC, KaterinBaranova commented on src/test/java/tests/CartHoverTest.java
> +        assertEquals(checkOutPage.getItemsInCart(),2);
Fixed expected result = 2 to be 1. test failed there is a bug on the app, and it shows "Your shopping cart contains: 2 product" but actually there is only one 
<img width="1172" alt="Screenshot 2022-02-17 at 22 33 22" src="https://user-images.githubusercontent.com/89603016/154558597-19b1544c-d752-4447-bdbb-57571aa59dae.png">

2022-02-17 19:52 UTC, KaterinBaranova commented on src/test/java/tests/SignInTest.java
> +    private final static String INVALID_USERNAME = "Katee1@test2.com";
Replaced according to the convention.

2022-02-17 19:56 UTC, KaterinBaranova commented on src/test/java/pages/ItemPage.java
> +        for (WebElement li : colors) {
Changed variable name.

2022-02-17 20:01 UTC, KaterinBaranova commented on src/test/java/tests/CartHoverTest.java
> +    public void checkOutFromHoverTest() {
Detailed description.

2022-02-17 20:18 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +        state.selectByIndex(1);
Removed hardcode, used FindBy and selectByVisibleText. (by mistake the name of this commit Detailed description.)

2022-02-17 20:18 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +        Select state = new Select(driver.findElement(By.id("id_state")));
Removed hardcode, used FindBy and selectByVisibleText. (by mistake the name of this commit Detailed description.)

2022-02-17 20:27 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +    public void fillPasswordField(String Password) {
Changed to lower case.

2022-02-17 20:54 UTC, KaterinBaranova commented on src/test/java/pages/CartHoverPage.java
> +    private List<WebElement> getCartItems() {
Used List cartItem.

2022-02-17 21:15 UTC, KaterinBaranova commented on src/test/java/pages/ItemPage.java
> +        getActions().isElementDisplayed(cartFrame);
Deleted extra code.

2022-02-17 21:24 UTC, KaterinBaranova commented on src/test/java/pages/WishlistPage.java
> +        return getCell(wishlistName) != null;
Removed unwanted code.

2022-02-17 21:25 UTC, KaterinBaranova commented on src/test/java/pages/WishlistPage.java
> +    private WebElement getCell(String wishlistName) {
Removed unwanted code.

2022-02-17 21:25 UTC, KaterinBaranova commented on src/test/java/pages/WishlistPage.java
> +                return wishlistTable.findElement(By.xpath("//*[contains(@class,\"table\")]/tbody/tr[" + rowNumberCounter + "]/td[" + ColumnNumber.NAME.columnNumber + "]"));
Removed unwanted code.

2022-02-17 21:27 UTC, KaterinBaranova commented on src/test/java/pages/WishlistPage.java
> +        List<WebElement> allRows = wishlistTable.findElements(By.xpath("//*[contains(@class,\"table\")]/tbody/tr[*]/td[1]"));
Removed unwanted code.

2022-02-18 06:00 UTC, KaterinBaranova commented on src/test/java/pages/ItemPage.java
> +    public void openItem(String productName) {
Created Catalog page.

2022-02-18 06:30 UTC, KaterinBaranova commented on src/test/java/pages/ItemPage.java
> +        driver.findElement(By.xpath("//a[contains(text(),'" + productName + "')]")).click();
 Removed the kindergarten used String.format.

2022-02-18 06:57 UTC, KaterinBaranova commented on src/test/java/pages/ItemPage.java
> +        List<WebElement> colors = colorOptions.findElements(By.xpath(".//*"));
Updated set color method.

2022-02-18 10:12 UTC, voropa commented on src/test/java/pages/CheckOutPage.java
> +    public void fillAddressTitle(String Other) {
переменная с большой буквы буквы

2022-02-18 10:16 UTC, KaterinBaranova commented on src/test/java/pages/CheckOutPage.java
> +    public void fillAddressTitle(String Other) {
Fixed

2022-02-18 10:25 UTC, voropa requested changes

2022-02-18 10:25 UTC, voropa commented on src/test/resources/RegressionTest.xml
> +            <run>
Do you really have any tests marked with "slow" group?

2022-02-18 10:25 UTC, voropa commented on src/test/resources/RegressionTest.xml
> +            <run>
Перепроверь в целом .xml фалы. Если ты все тесты разделила на smoke и regression и они все у тебя в аннотации @test помечены группой smoke/regression, то нет смысла в .xml файле разделять из на много <tests>.
Правильнее будет такая структура:
<suite name ="Regression/Smoke">
<test>
<groups>
<run>
<include name = "Smoke/regression"/>
</run>
</groups>
    <classes>
      <class name="*" />
    </classes>

Такой xml запустит все тесты из всех классов, которые помечены группой "smoke/regression"

2022-02-18 10:25 UTC, voropa commented on src/test/resources/RegressionTest.xml
> +            <run>
<suite name ="Regression/Smoke">
<test>
<groups>
<run>
<include name = "Smoke/regression"/>
</run>
</groups>
    <classes>
      <class name="*" />
    </classes>

2022-02-18 10:26 UTC, voropa commented on src/test/resources/RegressionTest.xml
> +            <run>
Почему то не отображается код...
прикреплю картинку
<img width="277" alt="image" src="https://user-images.githubusercontent.com/14195681/154664983-b6d69727-e8bc-4dde-bc83-14b535a13df0.png">

2022-02-18 11:58 UTC, KaterinBaranova commented on src/test/resources/RegressionTest.xml
> +            <run>
<img width="887" alt="Screenshot 2022-02-18 at 14 57 40" src="https://user-images.githubusercontent.com/89603016/154678890-30f583e4-fd1e-48b5-abff-dce5796d7aa1.png">
Подскажи пожалуйста а так можно делать?

2022-02-18 13:47 UTC, KaterinBaranova commented on src/test/resources/RegressionTest.xml
> +            <run>
Updated xml.

2022-02-18 14:00 UTC, voropa commented on src/test/resources/RegressionTest.xml
> -<suite name="Regression Test" parallel="tests" thread-count="2">
А чего ты удалила parallel и thread-count, если они запускались в параллель, то это же хорошо, пусть так и запускаются

2022-02-18 14:19 UTC, KaterinBaranova commented on src/test/resources/RegressionTest.xml
> -<suite name="Regression Test" parallel="tests" thread-count="2">
by mistake
added

2022-02-18 14:20 UTC, voropa approved these changes

2022-02-18 14:30 UTC, merged